defmodule Anime.Access.Catalog do
  @moduledoc "Permission snapshot from anime.md section 17; no dynamic permission atoms."
  @permissions [
    {"admin.panel.access", "открытие любого маршрута /admin/*"},
    {"admin.dashboard.view",
     "раздел Дашборд: количество пользователей, аниме, видео, онлайн, Uptime"},
    {"admin.stats.view",
     "посещения по дням и по странам, отчёты «Популярные запросы» и «Запросы без результатов» из п.6"},
    {"users.user.view",
     "список пользователей, поиск, фильтры, профиль пользователя, профиль заблокированного и запросившего удаление (п.11)"},
    {"users.user.edit", "правка ника, email, аватара и locale чужого аккаунта"},
    {"users.user.ban", "блокировка пользователя"},
    {"users.user.unban", "снятие блокировки до истечения срока"},
    {"users.user.delete", "удаление чужого аккаунта администратором"},
    {"users.role.assign", "смена роли пользователя"},
    {"users.session.revoke", "завершение чужих сессий и удаление чужих cookie «запомнить меня»"},
    {"users.activity.view", "раздел Пользователи / История активности"},
    {"roles.role.view", "экран «Роли»"},
    {"roles.role.create", "создание несистемной роли"},
    {"roles.role.edit", "переименование роли и выбор роли по умолчанию при регистрации"},
    {"roles.role.delete", "удаление несистемной роли"},
    {"roles.permission.view", "экран «Разрешения»"},
    {"roles.matrix.edit", "экран «Матрица прав», изменение матрицы роль x разрешение"},
    {"moderation.report.view",
     "раздел Модерация / Жалобы: CommentReport и жалобы на пользователя из /u/:nick (п.11)"},
    {"moderation.report.resolve", "решение по жалобе: принять, отклонить"},
    {"moderation.comment.view",
     "раздел Модерация / Комментарии, включая Comment со статусом «скрыт»"},
    {"moderation.comment.edit", "правка любого Comment без ограничения по времени (п.9)"},
    {"moderation.comment.hide", "перевод Comment в статус «скрыт» и обратно в «опубликован»"},
    {"moderation.comment.delete", "перевод Comment в статус «удалён»"},
    {"moderation.stopword.edit", "список стоп-слов на экране Модерация / Комментарии (п.9)"},
    {"moderation.content.view",
     "разделы Модерация / Пользовательский контент, Ожидающие проверки, Заблокированный контент"},
    {"moderation.content.review", "решение по элементу очереди проверки"},
    {"moderation.donation_comment.moderate",
     "статусы комментариев к Donation: на проверке, опубликован, скрыт (п.12)"},
    {"content.anime.view", "раздел Контент / Аниме"},
    {"content.anime.create", "создание Anime"},
    {"content.anime.edit",
     "правка полей Anime, постера, stage_id, связей AnimeGenre и AnimeCategory"},
    {"content.anime.delete", "удаление Anime"},
    {"content.anime.publish", "смена статуса публикации: черновик, опубликован, скрыт"},
    {"content.draft.view",
     "открытие Anime со статусом «черновик» и «скрыт» на /anime/:slug и его Episode на /watch/:slug/:season/:episode; на /catalog и /search такие тайтлы не выводятся ни одной роли (п.3, п.6)"},
    {"content.season.manage", "Season: создание, правка, удаление"},
    {"content.episode.manage", "Episode: создание, правка, удаление, превью"},
    {"content.genre.manage", "Genre, порядок и видимость значений в фильтрах каталога"},
    {"content.category.manage", "Category, состав и порядок категорий главной страницы (п.2)"},
    {"content.stage.manage", "Stage"},
    {"content.studio.manage",
     "раздел Контент / Студии: список значений поля «студия» Anime и переименование значения сразу во всех Anime"},
    {"content.relation.manage", "AnimeRelation, справочники типов и возрастных рейтингов"},
    {"content.homepage.pin", "закрепление аниме первым в категории на главной (п.2)"},
    {"video.upload.view",
     "раздел Видео / Все видео: VideoUpload со статусом обработки, прогрессом и текстом ошибки"},
    {"video.upload.create", "раздел Видео / Добавить видео, загрузка исходного файла в MinIO"},
    {"video.upload.delete", "удаление VideoUpload и связанных VideoRendition"},
    {"video.upload.retry",
     "перезапуск Oban-задачи транскодинга для VideoUpload со статусом ошибки"},
    {"video.source.view", "раздел Видео / Источники"},
    {"video.source.create", "создание VideoSource"},
    {"video.source.edit", "правка VideoSource и смена статуса доступности"},
    {"video.source.delete", "удаление VideoSource"},
    {"video.voiceover.manage", "VoiceOver: создание, правка, удаление"},
    {"video.subtitle.manage", "SubtitleTrack: загрузка файла VTT в MinIO, правка, удаление"},
    {"video.domain.manage",
     "список разрешённых доменов внешних embed на экране Видео / Источники (п.8)"},
    {"video.player.manage",
     "раздел Видео / Плееры: провайдеры внешних embed, код, название, шаблон адреса встраивания, признак включения"},
    {"video.error.view", "подраздел «Ошибки / недоступные видео» раздела Видео"},
    {"video.error.resolve",
     "закрытие записи об ошибке и снятие статуса «Требует проверки» (п.8)"},
    {"video.watch.play",
     "просмотр видео на публичной стороне: маршрут /watch/:slug/:season/:episode, кнопки «Смотреть» и «Продолжить», блок «Продолжить просмотр», список эпизодов со ссылками (п.16)"},
    {"video.settings.toggle",
     "переключатели Setting video_enabled и video_guest_enabled в разделе «Настройки / Основные» и поле Anime.video_enabled на экране правки аниме (п.16)"},
    {"blog.post.view", "раздел Блог / Записи: список, фильтры, карточка записи"},
    {"blog.post.create", "создание Post"},
    {"blog.post.edit", "правка полей Post, обложки, тегов и привязанного тайтла"},
    {"blog.post.publish",
     "смена статуса Post между draft, scheduled, published и hidden и задание published_at"},
    {"blog.post.pin", "закрепление записи в ленте и снятие закрепления"},
    {"blog.post.delete", "удаление Post"},
    {"blog.tag.manage", "PostTag: создание, правка, удаление, порядок"},
    {"blog.draft.view", "открытие Post со статусом draft, scheduled и hidden на /blog/:slug"},
    {"announcements.banner.manage", "раздел Объявления / Верхний баннер"},
    {"announcements.global.manage", "раздел Объявления / Глобальные уведомления: Announcement"},
    {"announcements.personal.send",
     "раздел Объявления / Персональные уведомления: Announcement с audience user и kind bell в паре полей title_ru, title_en, body_ru, body_en; порождённый Notification несёт event announcement_personal и payload с announcement_id"},
    {"announcements.notification.view",
     "раздел Объявления / Колокольчик: список отправленных Notification и число прочтений"},
    {"announcements.modal.manage", "раздел Объявления / Modal"},
    {"feedback.ticket.view", "разделы Обратная связь / Входящие, Открытые, В работе, Закрытые"},
    {"feedback.ticket.reply", "ответ на FeedbackTicket"},
    {"feedback.ticket.assign",
     "перевод FeedbackTicket в статус «в работе» и назначение исполнителя"},
    {"feedback.ticket.close", "закрытие FeedbackTicket"},
    {"feedback.template.manage", "раздел Обратная связь / Шаблоны ответов"},
    {"billing.transaction.view",
     "подраздел Транзакции, карточка Transaction, список WebhookEvent по ней"},
    {"billing.transaction.resolve",
     "разбор статуса «требует разбора» и пометки «конфликт» (п.12)"},
    {"billing.donation.view", "подраздел Донаты"},
    {"billing.donation.edit",
     "флаг публикации Donation, отображаемое имя, статус комментария не затрагивается"},
    {"billing.donor.link",
     "подраздел Донаты / Биллинг — Пользователи: привязка гостевого Donation к аккаунту (п.12)"},
    {"billing.refund.create", "инициирование полного и частичного возврата (п.12)"},
    {"billing.stats.view", "подраздел Статистика донатов"},
    {"audit.log.view", "раздел Журнал действий"},
    {"audit.log.export", "выгрузка выборки AuditLog файлом"},
    {"settings.general.edit", "Настройки / Основные"},
    {"settings.seo.edit", "Настройки / SEO"},
    {"settings.email.edit", "Настройки / Email"},
    {"settings.registration.edit",
     "Настройки / Регистрация, включая флаг включения /register (п.11)"},
    {"settings.notifications.edit", "Настройки / Уведомления"},
    {"settings.security.edit", "Настройки / Безопасность"},
    {"system.queue.view", "очереди Oban: список, задачи, ошибки"},
    {"system.queue.manage", "пауза, возобновление, повтор и отмена задач Oban"},
    {"system.cron.view", "список периодических задач"},
    {"system.cron.manage", "включение, выключение и ручной запуск периодической задачи"},
    {"system.cache.clear", "сброс таблиц ETS приложения"},
    {"system.storage.view", "состояние MinIO: бакеты, объём, ошибки выгрузки"},
    {"system.storage.manage", "удаление объектов MinIO и запуск сверки хранилища"},
    {"system.database.view", "состояние PostgreSQL: размер, соединения, миграции"},
    {"system.log.view", "раздел Система / System logs"}
  ]
  def permissions, do: @permissions
  def codes, do: Enum.map(@permissions, &elem(&1, 0))
  def role_codes("owner"), do: codes()
  def role_codes("user"), do: ["video.watch.play"]

  def role_codes("admin"),
    do:
      codes() --
        ~w(roles.role.create roles.role.edit roles.role.delete roles.matrix.edit settings.security.edit system.storage.manage system.database.view)

  def role_codes("comment_moderator") do
    ~w(video.watch.play admin.panel.access admin.dashboard.view users.user.view users.activity.view users.user.ban users.user.unban) ++
      Enum.filter(codes(), &String.starts_with?(&1, "moderation."))
  end

  def role_codes("content_editor") do
    ~w(admin.panel.access admin.dashboard.view) ++
      Enum.filter(
        codes(),
        &(String.starts_with?(&1, ["content.", "blog.", "video."]) and
            &1 not in ~w(video.domain.manage video.player.manage))
      )
  end

  def role_codes(_), do: []
end
